In [1]:
import pnet_loader
import util
import torch
import seaborn as sns
import pandas as pd
import numpy as np
import Pnet
import random
import pickle
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
import os

%load_ext autoreload
%autoreload 2

Generate small test dataset

In [2]:
# rna_ext_val = pd.read_csv('/mnt/disks/pancan/data/mel_dfci_2019/data_RNA_Seq_expression_tpm_all_sample_Zscores.txt',
#                           delimiter='\t').set_index('Hugo_Symbol').T.drop('Entrez_Gene_Id').dropna(axis=1)
# cna_ext_val = pd.read_csv('/mnt/disks/pancan/data/mel_dfci_2019/data_CNA.txt',
#                           delimiter='\t').set_index('Hugo_Symbol').T.dropna(axis=1)
# ext_val = pd.read_csv('/mnt/disks/pancan/data/mel_dfci_2019/data_clinical_sample.txt',
#                              delimiter='\t').set_index('Sample Identifier').iloc[4:]
# important_genes = list(pd.read_csv('/mnt/disks/pancan/m1000/cancer_genes.txt')['genes'].values)
# joint_genes = list(set(important_genes).intersection(list(rna_ext_val.columns), list(cna_ext_val.columns)))
# gene_list = random.sample(joint_genes, 500)
# random_genes_a = list(rna_ext_val.sample(5, axis=1).columns)
# random_genes_b = list(cna_ext_val.sample(5, axis=1).columns)
# joint_samples = list(rna_ext_val.sample(20).join(cna_ext_val, rsuffix='_cna', how='inner').index)
# random_samples_a = list(rna_ext_val.sample(5, axis=0).index)
# random_samples_b = list(cna_ext_val.sample(5, axis=0).index)
# random_samples_c = list(cna_ext_val.sample(5, axis=0).index)
# random_samples_d = list(cna_ext_val.sample(5, axis=0).index)
# test_rna = rna_ext_val.loc[joint_samples+random_samples_a][joint_genes+random_genes_a].copy().drop_duplicates()
# test_cna = cna_ext_val.loc[joint_samples+random_samples_b][joint_genes+random_genes_b].copy().drop_duplicates()
# test_add = ext_val.loc[joint_samples+random_samples_c][['Purity', 'Ploidy']].copy().drop_duplicates()
# test_y = ext_val.loc[joint_samples+random_samples_d][['Heterogeneity']].copy().drop_duplicates()
# test_rna.reset_index(inplace=True)
# test_cna.reset_index(inplace=True)
# test_add.reset_index(inplace=True)
# test_y.reset_index(inplace=True)
# test_rna.rename(columns={'index': 'sample_id'}, inplace=True)
# test_cna.rename(columns={'index': 'sample_id'}, inplace=True)
# test_add.rename(columns={'Sample Identifier': 'sample_id'}, inplace=True)
# test_y.rename(columns={'Sample Identifier': 'sample_id'}, inplace=True)
# test_rna.to_csv('../data/test_data/rna.csv', index=False)
# test_cna.to_csv('../data/test_data/cna.csv', index=False)
# test_add.to_csv('../data/test_data/add.csv', index=False)
# test_y.to_csv('../data/test_data/y.csv', index=False)
# with open('../data/test_data/gene_sublist.txt', 'wb') as fp:
#     pickle.dump(gene_list, fp)

Read test data

In [3]:
test_rna = pd.read_csv('../data/test_data/rna.csv').set_index('sample_id')
test_cna = pd.read_csv('../data/test_data/cna.csv').set_index('sample_id')
test_add = pd.read_csv('../data/test_data/add.csv').set_index('sample_id')
test_y = pd.read_csv('../data/test_data/y.csv').set_index('sample_id')

with open('../data/test_data/gene_sublist.txt', 'rb') as fp:
    gene_list = pickle.load(fp)

In [4]:
genetic_data = {'rna': test_rna, 'cna': test_cna}

In [5]:
train_dataset, test_dataset = pnet_loader.generate_train_test(genetic_data,
                                                              test_y, 
                                                              additional_data=test_add,
                                                              test_split=0.2,
                                                              gene_set=gene_list,
                                                              collinear_features=2)

Given 2 Input modalities
Found 20 overlapping indicies
Initializing Train Dataset
Found 500 overlapping genes
generated input DataFrame of size (16, 1000)
Initializing Test Dataset
Found 500 overlapping genes
generated input DataFrame of size (4, 1000)
Replace input of: BLM_cna with collinear feature.
Replace input of: TBX3 with collinear feature.


In [6]:
assert set(gene_list) == set(train_dataset.genes), 'Training dataset expected to have the same gene set as in file'
assert train_dataset.genes == list(train_dataset.input_df.columns)[:500], 'Training data genes should be ordered \
                                                                            as stored in the genes variable'
assert train_dataset.input_df.shape == torch.Size([16, 1000]), 'Input DataFrame expected to be a of size\
                                                        [16, 1000], got: {}'.format(train_dataset.input_df.shape)
assert train_dataset.x.shape == torch.Size([16, 1000]), 'Small train dataset expected to be a tensor of size\
                                                        [16, 1000], got: {}'.format(train_dataset.x.shape)
assert train_dataset.y.shape == torch.Size([16, 1]), 'Small train dataset expected to be a tensor of size\
                                                        [16, 1], got: {}'.format(train_dataset.y.shape)


In [7]:
import ReactomeNetwork

In [8]:
reactome_network = ReactomeNetwork.ReactomeNetwork(train_dataset.get_genes())

Found 500 overlapping genes


In [9]:
train_loader, val_loader = pnet_loader.to_dataloader(train_dataset, test_dataset, 64)

In [133]:
test_y_bin = test_y.apply(lambda x: round(2*x))
pd.get_dummies(test_y_bin.astype('long'), 'Heterogeneity')

Heterogeneity
sample_id               
Sample159              1
Sample146              0
Sample117              1
Sample10               1
Sample61               0
Sample17               0
Sample24               0
Sample78               0
Sample45               0
Sample134              0
Sample1                1
Sample141              0
Sample184              0
Sample20               0
Sample14               1
Sample189              1
Sample83               0
Sample47               0
Sample165              0
Sample196              0
Sample44               1
Sample58               0
Sample86               1
Sample56               0

In [134]:
model, train_scores, test_scores, train_dataset, test_dataset = Pnet.run(genetic_data,
                                                                         test_y_bin,
                                                                         verbose=True,
                                                                         early_stopping=True,
                                                                         epochs=10,
                                                                        )

Task defined: BC 
 if this is not the intended task please specify task
Given 2 Input modalities
Found 20 overlapping indicies
Initializing Train Dataset
Found 649 overlapping genes
generated input DataFrame of size (16, 1298)
Initializing Test Dataset
Found 649 overlapping genes
generated input DataFrame of size (4, 1298)
Found 649 overlapping genes
Loss function used: BCEWithLogitsLoss()
Epoch 1 of 10
Train Loss: 1.2823991775512695
Test Loss: 1.4118282794952393
Epoch 2 of 10
Train Loss: 1.2894823551177979
Test Loss: 1.4125237464904785
Epoch 3 of 10
Train Loss: 1.2473118305206299
Test Loss: 1.4132188558578491
Epoch 4 of 10
Train Loss: 1.2277729511260986
Test Loss: 1.413933515548706
Epoch 5 of 10
Train Loss: 1.2076926231384277
Test Loss: 1.4146549701690674
Epoch 6 of 10
Train Loss: 1.1683881282806396
Test Loss: 1.4153600931167603
Epoch 7 of 10
Train Loss: 1.1836776733398438
Test Loss: 1.4160659313201904
Epoch 8 of 10
Train Loss: 1.1784753799438477
Test Loss: 1.4167823791503906
Epoch 9 

In [54]:
x_train = train_dataset.x
additional_train = train_dataset.additional
y_train = train_dataset.y
x_test = test_dataset.x
additional_test = test_dataset.additional
y_test = test_dataset.y

In [49]:
model.to('cpu')
pred = model.predict(x_test, additional_test)


In [49]:
x = torch.randn(1, 3)
x

tensor([[ 1.1193,  0.0246, -0.9385]])

In [44]:
a =torch.randint(10,(10,1))

In [45]:
import torch.nn as nn

In [35]:
m(a[1])

tensor([0.5792, 0.5397])

In [36]:
a[1]

tensor([0.3194, 0.1592])